apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: services-watcher
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mc-router-services-watcher
subjects:
- kind: ServiceAccount
  name: mc-router
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: services-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: mc-router
spec:
  type: NodePort
  ports:
  - targetPort: web
    name: web
    port: 8080
  - targetPort: proxy
    name: proxy
    port: 25565
    nodePort: 30001
  selector:
    app: mc-router
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mc-router
  name: mc-router
spec:
  selector:
    matchLabels:
      app: mc-router
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mc-router
    spec:
      serviceAccountName: mc-router
      containers:
      - image: itzg/mc-router:latest
        name: mc-router
        args: ["--api-binding", ":8080", "--in-kube-cluster"]
        ports:
        - name: proxy
          containerPort: 25565
        - name: web
          containerPort: 8080