apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: rcon-web-admin
  name: rcon-web-admin
spec:
  selector: 
    matchLabels:
      app: rcon-web-admin
  template:
    metadata:
      labels:
        app: rcon-web-admin
    spec:
      containers:
      - name: rcon-web-admin
        image: itzg/rcon
        env:
        - name: RWA_USERNAME
          value: admin 

        - name: RWA_PASSWORD
          value: {{ .Values.rconWebPassword }}
  
        - name: RWA_ADMIN
          value: "TRUE"
     
        - name: RWA_RCON_HOST
          value: {{ template "minecraft.fullname" . }}
      
        - name: RWA_RCON_PASSWORD
          value: {{ .Values.rconPassword }}

        - name: RWA_WEBSOCKET_URL_SSL 
          value: wss://192.168.86.3:31001

        - name: RWA_WEBSOCKET_URL
          value: ws://192.168.86.3:31001
        
        ports:
        - containerPort: 4326
        - containerPort: 4327
---
apiVersion: v1
kind: Service
metadata:
  name: rcon-web
spec:
  type: ClusterIP
  selector:
    app: rcon-web-admin
  ports:
  - name: web
    port: 4326
    targetPort: 4326
---
apiVersion: v1
kind: Service
metadata:
  name: rcon-websockets
spec:
  type: NodePort
  selector:
    app: rcon-web-admin
  ports:
  - name: websocket
    port: 4327
    targetPort: 4327
    nodePort: 31001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: rcon-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /{{ template "minecraft.fullname" . }}(/|$)(.*)
        pathType: Prefix
        backend: 
          service:
            name: rcon-web
            port: 
              number: 4326