apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{"longhorn.io/volume-scheduling-error":"","pv.kubernetes.io/provisioned-by":"driver.longhorn.io"},"creationTimestamp":"2022-07-30T22:44:31Z","finalizers":["kubernetes.io/pv-protection","external-attacher/driver-longhorn-io"],"name":"pvc-72da7409-f643-41d4-999a-c421a18baf89","resourceVersion":"297233","uid":"ecc2b64f-0fa5-4729-83bf-05ac6bb59935"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"5Gi"},"csi":{"driver":"driver.longhorn.io","fsType":"ext4","volumeAttributes":{"dataLocality":"disabled","fromBackup":"","fsType":"ext4","numberOfReplicas":"2","staleReplicaTimeout":"30","storage.kubernetes.io/csiProvisionerIdentity":"1659190394763-8081-driver.longhorn.io"},"volumeHandle":"pvc-72da7409-f643-41d4-999a-c421a18baf89"},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"longhorn","volumeMode":"Filesystem"},"status":{"phase":"Released"}}
    longhorn.io/volume-scheduling-error: ""
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
  creationTimestamp: "2022-07-30T22:44:31Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/driver-longhorn-io
  name: pvc-72da7409-f643-41d4-999a-c421a18baf89
  resourceVersion: "297992"
  uid: ecc2b64f-0fa5-4729-83bf-05ac6bb59935
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataLocality: disabled
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "2"
      staleReplicaTimeout: "30"
      storage.kubernetes.io/csiProvisionerIdentity: 1659190394763-8081-driver.longhorn.io
    volumeHandle: pvc-72da7409-f643-41d4-999a-c421a18baf89
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  volumeMode: Filesystem
