persistence:
  config:
    enabled: true
    type: pvc

    mountPath: /config
    readOnly: false

    existingClaim: pvc-sonarr
    accessMode: ReadWriteOnce
    retain: true

  data:
    enabled: true
    type: pvc

    mountPath: /data

    existingClaim: data-pvc

service:
  main:
    ports:
      http:
        port: 80
        targetPort: 8989

metrics:
  enabled: true
  exporter: 
    port: 9794

node_selector:
  videos: true

env:
  TZ: America/New York