- hosts: workers
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes

  tasks:
  - name: delete /etc/kubernetes
    file:
      state: absent
      path: /etc/kubernetes

  - name: delete /var/lib/etcd
    file:
      state: absent
      path: /var/lib/etcd
  
  - name: delete /etc/cni/net.d/
    file:
      state: absent
      path: /etc/cni/net.d/

  - name: clear kubeadm 
    shell: sudo kubeadm reset -f

  - name: Copy join command from Ansiblehost to the worker nodes.
    become: yes
    copy:
      src: /tmp/kubernetes_join_command
      dest: /tmp/kubernetes_join_command
      mode: 0777

  - name: Join the Worker nodes to the cluster.
    become: yes
    command: sudo sh /tmp/kubernetes_join_command
    register: joined_or_not